sudo: required
dist: precise
language: cpp

notifications:
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-4.9
            - python
            - python3.4
            - python3.4-dev
            - swig
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-5
            - python
            - python3.4
            - python3.4-dev
            - swig
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - deadsnakes
          packages:
            - clang-3.6
            - python
            - python3.4
            - python3.4-dev
            - swig
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - deadsnakes
          packages:
            - clang-3.7
            - python
            - python3.4
            - python3.4-dev
            - swig
      env: COMPILER=clang++-3.7

before_script:
  - sudo updatedb

script:
  - make CXX=$COMPILER devel
  - make CXX=$COMPILER PYTHON=3.4 devel
